# Generated by Django 4.2.13 on 2024-12-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_room_room_number_room_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.FloatField(),
        ),
    ]
