# Generated by Django 4.2.13 on 2024-12-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_room_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
